### ISSUE TITLE
Feature request: hostiles don't reveal

### ISSUE THREAD

**Issue by tirzah2** [CarlosFdez/world-explorer#35]
Hi Carlos! Great module!
In about 10 days I start a West marches campaign, and I was thinking to put wandering monsters and wandering merchants on the hex map. The only issue is that when they move (I use module Patrol) they reveal the map.

Any solution to that?

Kindest regards

**Comment by farling42** [comment]
Do the tokens have vision enabled?

**Comment by CarlosFdez** [comment]
Even if they did, that probably still reveals. Its a very late reply (sorry about that), but I can try to knock this out today.

**Comment by CarlosFdez** [comment]
Should be addressed in World Explorer 0.9.0. Now hostile tokens should no longer auto-reveal map hexes. Please re-open and clarify if that's not what you were talking about.

**Comment by 13jtibbitts** [comment]
This doesn't appear to solve the issue, at least not for Pathfinder 2e. That may be because you can't directly set token disposition, but you change the actor sheet's alliance to Opposition, Neutral, or Party.

**Comment by CarlosFdez** [comment]
I probably should have tested pf2e, given that's generally what I'm actually devving. I'll look into it later.

**Comment by farling42** [comment]
Should reveal only be done by Friendly/Party tokens, rather than allowing Neutral tokens to reveal it (since Neutral probably aren't controlled by PCs)?

**Comment by CarlosFdez** [comment]
Its currently set so only friendly and player owned can reveal. The issue is that the party sheet is not player owned by default, so player owned alone isn't enough.

I'll either see if there's something I can tweak PF2e side (make disposition reflect alliance a bit better) or changed the condition to "if at least one player has observer permission". When I did this change I tested in 5e to make sure I wasn't using any pf2e specific api.

**Comment by CarlosFdez** [comment]
> This doesn't appear to solve the issue, at least not for Pathfinder 2e. That may be because you can't directly set token disposition, but you change the actor sheet's alliance to Opposition, Neutral, or Party.

I'm playing with it again, I guess I don't understand what the current issue is. NPCs don't permanently reveal tiles, and players do. Parties should, but they have neutral disposition, I'll have to make them friendly disposition if they're all friendly.

NPCs do reveal tiles, but only to the GM and they're not persisted. They were persisted before. I can imagine that lack of consistency being an issue though, so it may be worth tightening that.

**Comment by CarlosFdez** [comment]
I have a fix for world explorer, but it'll break party actor reveal. Once https://github.com/foundryvtt/pf2e/pull/11716 goes through and an update is released with that tweak, I'll release a new update of this module.

**Comment by CarlosFdez** [comment]
Its done. The Token Reveal should be the same as the Keep Areas Explored setting. Please report if there's an issue. It should be quicker to respond this time now that pf2e has been updated so that party alliances should be as expected.
